### ISSUE TITLE
Task pendent deleted with command CLEAR 

### ISSUE THREAD

**Issue by sdnnvs** [perryrh0dan/taskline#1]
Hi, look the task 2...

![Captura de tela de 2019-09-20 12-39-04](https://user-images.githubusercontent.com/55322151/65340229-2f86e580-dba4-11e9-9530-ed9520d9d583.png)

**Comment by perryrh0dan** [comment]
Hi sdnnvs,

thanks for the issue. I will directly have a look on it.

**Comment by perryrh0dan** [comment]
Problem should be solved now. Version 1.0.5 is the newest one. At the moment its only on npm will publish soon also to snapcraft.
