### ISSUE TITLE
Unable to parse date with December

### ISSUE THREAD

**Issue by AndreyPikunov** [perryrh0dan/taskline#11]
I've just installed taskline on my **Ubuntu 18.04.3 LTS** via snap so I have the latest version **(1.1.1)**.
When I try to do smth like this:
`tl -t "Sample task" -d "01.12.2019"`
I see this error:
` ✖  Unable to parse date: 01.12.2019`

I checked whether it's possible to use "00" instead "12" for December -- Yes, It works, but obviously this way gives December 1, 2018; not what I really need: December 1, 2019. 
`tl due 1 "01.00.2019"`
` ✔  Updated duedate of task: 1 to Sat Dec 01 2018 00:00:00 GMT+0300 (Moscow Standard Time)`

**Comment by perryrh0dan** [comment]
Hi Andrey thanks for reporting the bug. I fixed the issue and released a new version (1.1.2) in the snapcraft beta channel. You can checkout the version from there.

**Comment by AndreyPikunov** [comment]
Oh, Now It seems to work correctly.
Thank you, I like this app!
