### ISSUE TITLE
Duplicate software?

### ISSUE THREAD

**Issue by smith558** [perryrh0dan/taskline#31]
What's the difference between [taskbook](https://github.com/klaussinani/taskbook) and [taskline](https://github.com/perryrh0dan/taskline)? These 2 apps seem identical, even the walk-through screenshots are identical in content.

Just trying to figure out if these 2 are forks or developed independently or cooperating in any way. If not, which is better?

**Comment by perryrh0dan** [comment]
Hi @smith558, taskbook was developed a long time before taskline, I started using taskbook in 2019 but i missed some features in taskbook. So i started taskline, a complete independent rebuild of taskbook in typescript. And add lots of cool new features like:
- Sync tasks across all your devices with firestore.
- Advanced duedate functionality
- Custom color themes
- New list filter attributes
- Possibility to use id ranges
- Possibility to cancel tasks
- Possibility to rearrange item ids
- Timetracking for tasks
- Multilanguage support

I hope that helps you.

**Comment by smith558** [comment]
Thx for fast response!

**Comment by spasquali-ww** [comment]
This is a great port. You've added features and tightened some aspects of taskbook. That being said, given that the taskline interface and even the readme plainly follows the taskbook design, and as you say above you rewrote code from taskbook to make taskline, the name similarity, etc, maybe a nice, visible, thank you to taskbook? I may have missed that, but I looked through the readme and didn't see any mention of taskbook.

**Comment by perryrh0dan** [comment]
Hi @spasquali-ww,

Thank you for the kind words. You are right at the moment taskbook is only mentioned in the license file. But i will think about a banner in the readme.

Best Regards
Thomas

**Comment by chmac** [comment]
Any update on adding this? It took me a while to figure out what was going on because the project descriptions and readmes look identical for the first few lines. Also given that taskbook seems to be unmaintained, it would likely help people to figure out that this is a TypeScript rewrite with added features...

**Comment by smith558** [comment]
Reopened as there seems to be an interest in this.

**Comment by AbhishekAmin** [comment]
1. It would help everyone if you explained the need to rewrite the entire piece of software just to introduce types and why you couldn't just add them on top of the original repo.

2. I scanned through the readme very quickly and found no credit or mention of Taskbook, which in my opinion should be in H1 tag at the very top.

**Comment by perryrh0dan** [comment]
You guys are right. I have updated the readme: https://github.com/perryrh0dan/taskline/blob/master/readme.md#highlights and linked directly to the original project. But I would also like to mention that besides the same interface to the user, Taskbook and Taskline are two completely independent projects and the code has been completely rewritten and from my perspective much more modular and maintainable.
