### ISSUE TITLE
[feature request] add support for verbal dates

### ISSUE THREAD

**Issue by MartinsMednis** [perryrh0dan/taskline#4]
This is a feature request, an idea and a proposal of how it would look like when implemented.

The idea is this - when user creates a task or sets a due date, taskline would allow dates like: 
* today
* tonight
* tomorrow

Such dates would also require intelligent determination of time component in tadetimes. The configuration json file could be a place to set default value for time when only date is provided. For example, a default time is set to "18:00". When a task is created with due date "today", taskline would supplement the due datetime with configured time, i.e. "18:00". However, when user creates a task for today and it's already past the default due time, then taskline would add few hours and set the due date as "now() + 2 hours".

**Here is a list of proposed intelligent datetime combinations:**

* `today` - translates to todays date + preconfigured (i.e. 18:00) or calculated time;
* `tonight` - translates to todays date + another preconfigured time, i.e. 22:00;
* `tomorrow` - translates to tomorrow's date + preconfigured (i.e. 18:00) or calculated time;

**Combinations of two words (using `next` keyword):**
* `next week` - translates to the date of the same weekday in the next week
* `next month` - translates to the first working day of the next month
* `next year` - translates to the first working day of the next year
* `next Wednesday` - translates to the date of Wednesday in next week
* `Wednesday` - simple a weekday would translates to the date of next required weekday.

**Combinations of two words (using `in` keyword):**
* `in 3 weeks` - translates to the date after 3 weeks;
* `in 2 months` - translates to the same date after two months

**Examples**
```bash
$ tl t "Change the light bulb" -d "2019-11-05 18:00"     # current way of setting due dates
$ tl t "Change the light bulb" -d today
$ tl t "Fix the furniture" -d next week
$ tl t "Buy Christmas presents" -d in 2 months
```

**Comment by perryrh0dan** [comment]
Hi Martins, 

thanks for the feature request i will have a closer look soon. 
Unfortunately I have a lot to do at the moment.

BR
Thomas

**Comment by perryrh0dan** [comment]
Hi Martins, 

it took some time but now its possible to test a first version of verbal dates in the beta channel of taskline. Big Thanks to [Aditya Sriram](https://github.com/aditya95sriram) for providing the implementation.

**Comment by perryrh0dan** [comment]
Version 1.2.1 is now released as snap and npm package.
