### ISSUE TITLE
Possibility to change the colors? 

### ISSUE THREAD

**Issue by pergeri** [perryrh0dan/taskline#5]
Hi, 

I'm using terminator as my go-to terminal and it seems that TL clashes a bit with darker themes overall where a lot of things become basically impossible to see. 

Screenshots: https://imgur.com/sV7lykf 

I don't know if there's a way around it or if there is any config that can be done to change all text to use the color from an uncomplete task?

**Comment by perryrh0dan** [comment]
Hi pergeri, 

Yes I am currently working on such a functionality. Hopefully i can release the new version this weekend. If you are using snap you can checkout the beta channel. In the readme in the dev branch is also a small description how to configure the colors.

**Comment by pergeri** [comment]
Worked like a charm, great work on this btw, I will use it a lot! :) 

Looking forward to the stable :+1:
