### ISSUE TITLE
[feature request] time logging on tasks

### ISSUE THREAD

**Issue by twhitson** [perryrh0dan/taskline#6]
It would be nice to add the ability to log time to tasks. This could be useful for those who keep track of their time for work.

**Comment by perryrh0dan** [comment]
Hi twhitson,

We could save the time between starting and finishing a task. Is that what you are looking for ?

**Comment by twhitson** [comment]
@perryrh0dan I would prefer a manual way to log time against tasks. My company uses Jira so being able to quickly add some time as I finish small portions of the task would be very useful. I don't like tracking time between start and finish because if I get up for lunch or leave the office and pick it back up in the morning, I don't want that time tracked.

**Comment by sneakyx** [comment]
Hi, 
first, @perryrh0dan this is a nice tool - thanks for that!
In additon for the feature request:
Better would be something like a stopwatch with start/resume, pause, finish.
You can store everything in to variables for every task: the passed time in one variable, and the last start/resume time in another. 
When user starts a task, passedTime is empty, lastStartTime is set to the actual time. 
When user selects finished or pause, the difference between actualTime and lastStartTime is added to past time.
When user selects resume, just set lastStartTime to actualTime. (like "start", but without setting passedTime to zero).

**Comment by perryrh0dan** [comment]
Hi @sneakyx, 
I'm glad that you like the tool.
Tasks can already be started, paused and finished. Like you mentioned we only have to store the passedTime and the lastStartTIme in the entity. I will work on this feature and hopefully in the next days i will create a new release :)

**Comment by perryrh0dan** [comment]
hi @sneakyx 
where do you think should we display the passedTime ?
Maybe like this ? 

![passedTime](https://user-images.githubusercontent.com/28621009/81568273-d3c0d500-939d-11ea-9465-5893e1e20a5b.png)

**Comment by sneakyx** [comment]
If you mean the hours in the round brackets, that looks perfect to me.
By the way I read the documentation and now I know how to pause the task. (I didn't see the pause in docu).
And I already forked taskline to add next days the german documentation.

**Comment by perryrh0dan** [comment]
Feature was added in release 1.4.0. Thx for all the help :)

**Comment by sneakyx** [comment]
Sorry to bother again with this feature. In snapstore there is only V 1.2.2 available. (And it sais, it is updated on 11.05.2020). Do you have the possibility to update the version there or is this done automatically?

**Comment by perryrh0dan** [comment]
Hi @sneakyx,
I am sorry for the circumstances. Now version 1.4.0 is als available in the snap store :) I had to fix some packaging problems

**Comment by sneakyx** [comment]
Sorry, to bother You again with this feature. Seems, like there is a bug in there.
I started the task with id 16 about 2 hours ago...
The task with id 15  i started yesterday, but 441486.78 is also a bit too much... ;-)
![Bildschirmfoto_2020-05-13_08-42-09](https://user-images.githubusercontent.com/20614860/81779942-f534d480-94f5-11ea-90f6-da8681b7549e.png)

**Comment by sneakyx** [comment]
Additional info, maybe 441486.78 is Unix Timestamp 0?
And maybe the 5.x hours is 0:00 in some time zone- or the calculation is in different time zones...

**Comment by perryrh0dan** [comment]
Hi @sneakyx,
bugs should be fixed now. hopefully :) Release is on the way. Sadly you have to manually delete the stored time from the storage.json file in order to reset the passedTime.
