### ISSUE TITLE
Second example of due date is faulty

### ISSUE THREAD

**Issue by aditya95sriram** [perryrh0dan/taskline#8]
The second example in the "Due date" section (https://github.com/perryrh0dan/taskline#set-duedate) doesn't do what one would expect it to do. 
Instead, to obtain the desired effect, one needs to put the entire date string within quotes
`tl due 1,2,23 "15.09.2019 13:15"`. 

This is an easy bug to fix, but I also feel that this could be treated as a feature request to allow `tl due` command to swallow the entire string that follows as its argument rather than just the first item from a space-separated list of items (as it currently does and as is natural for shell commands).

**Comment by perryrh0dan** [comment]
Hi aditya, you are absolutly right thats an error in the readme file.

I think its better to keep it the way it is. To keep the application consistency. All parameters that contain a space have to be surrounded by "". It would be kind of confusing when you have to use quotes in the create command but dont have to use them in the due command. What do you think ?

**Comment by aditya95sriram** [comment]
Yes, your point makes sense, I didn't think of it that way.

You may close this issue after fixing the example in the readme.
