### ISSUE TITLE
How about a no-color output when the running terminal is not interactive

### ISSUE THREAD

**Issue by wari** [perryrh0dan/taskline#9]
I'd love to `tl | something` or in vim `:r!tl` and the colors are messing up the text. There should be a `--nocolor` mode and/or should detect that the terminal is not interactive.

This would be useful for further processing.

**Comment by aditya95sriram** [comment]
Can you give a small example, because when I try to do `:r!tl`, I don't see any weird artifacts arising due to the colors, other than the spacing/indenting used for formatting. I don't if this matters but I'm on Ubuntu 18.04 and using zshell.

**Comment by wari** [comment]
Unfortunately, I don't remember which host I have the issue with. I don't see this on the host I'm on at the moment. It could be an older version or incompatible terminal.

Anyway, since the behaviour is what I expected it to do, I'm closing this. Thanks @aditya95sriram
